"""client table and new fields

Revision ID: 2e19ae975961
Revises: 4f2e77a99091
Create Date: 2019-05-20 15:18:07.401421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e19ae975961'
down_revision = '4f2e77a99091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('addr', sa.String(length=250), nullable=True),
    sa.Column('contact_person_name', sa.String(length=150), nullable=True),
    sa.Column('contact_person_phone', sa.String(length=10), nullable=True),
    sa.Column('contact_person_email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_country'), 'client', ['country'], unique=False)
    op.create_index(op.f('ix_client_name'), 'client', ['name'], unique=True)
    op.add_column('user', sa.Column('inn', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'inn')
    op.drop_index(op.f('ix_client_name'), table_name='client')
    op.drop_index(op.f('ix_client_country'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
