"""driver table

Revision ID: 59bfea4a6164
Revises: 2e19ae975961
Create Date: 2019-05-21 09:50:52.495841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bfea4a6164'
down_revision = '2e19ae975961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('inn', sa.String(length=50), nullable=True),
    sa.Column('licence', sa.String(length=200), nullable=True),
    sa.Column('car', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('addr', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('med_licence', sa.String(length=100), nullable=True),
    sa.Column('med_licence_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn')
    )
    op.create_index(op.f('ix_driver_name'), 'driver', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_name'), table_name='driver')
    op.drop_table('driver')
    # ### end Alembic commands ###
