"""orders and stores

Revision ID: 6efa572f1cd4
Revises: 59bfea4a6164
Create Date: 2019-05-21 11:20:29.370827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efa572f1cd4'
down_revision = '59bfea4a6164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('addr', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('free_place', sa.Integer(), nullable=True),
    sa.Column('load_place', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_store_code'), 'store', ['code'], unique=True)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('addr_from', sa.String(length=250), nullable=True),
    sa.Column('addr_to', sa.String(length=250), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_client_id'), 'order', ['client_id'], unique=False)
    op.create_index(op.f('ix_order_date_to'), 'order', ['date_to'], unique=False)
    op.create_index(op.f('ix_order_driver_id'), 'order', ['driver_id'], unique=False)
    op.add_column('client', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_client_contact_person_phone'), 'client', ['contact_person_phone'], unique=True)
    op.create_unique_constraint(None, 'client', ['contact_person_email'])
    op.create_unique_constraint(None, 'client', ['fax'])
    op.create_unique_constraint(None, 'client', ['email'])
    op.create_unique_constraint(None, 'client', ['phone'])
    op.create_foreign_key(None, 'client', 'user', ['manager_id'], ['id'])
    op.create_unique_constraint(None, 'driver', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver', type_='unique')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_index(op.f('ix_client_contact_person_phone'), table_name='client')
    op.drop_column('client', 'manager_id')
    op.drop_index(op.f('ix_order_driver_id'), table_name='order')
    op.drop_index(op.f('ix_order_date_to'), table_name='order')
    op.drop_index(op.f('ix_order_client_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_store_code'), table_name='store')
    op.drop_table('store')
    # ### end Alembic commands ###
